apiVersion: v1
kind: Deployment
metadata:
  name: test
  labels:
    app: nginx
    name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      name: nginx
  template:
    metadata:
      labels:
        app: nginx
        name: nginx
    spec:
      container:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80